### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by patdx** [patdx/package-exports-analyzer#6]
- [ ] parse JSON with [momoa](https://github.com/humanwhocodes/momoa)
- [x] show all exports for some condition (similar to "list-exports")
- [x] add "react-native" export condition
- [x] click to navigate to dependency
- [ ] include other fields like main/module/es2015/etc (including Angular fields)
- [ ] add customizable test cases
- [ ] set test case expected result and show if satisfied or not
- [x] allow loading a real package json
- [ ] integrate different algorithms like the rollup node resolve, enhanced-resolve, vite resolve, [resolve](https://github.com/browserify/resolve)
   - resolve may be the most complete and portable version
- [ ] typescript type resolution for different cases and typescript versions
- [x] show how deno does it
- [ ] use mobile-friendly editor for smartphone
- [ ] embed state in sharable urls
- [ ] set up autocomplete for package json (using json schema in monaco?)
- [x] investigate [typescript resolve function](https://github.com/microsoft/TypeScript/blob/main/src/compiler/moduleNameResolver.ts)
- [ ] add unit tests
   - [ ] I think in order to show inline feedback I would need to fork an existing resolve fn and add support for JSON ast with line numbers
      - or, it may be possible to rewrite each path as a unique id, run the resolve function on that, then use the unique id to figure out which actual path was resolved
- [ ] add a feature to rewrite the export map in webpack's pseudocode format
- [x] support nested package jsons
- [ ] add package json "linter"
   - for example: https://github.com/skypackjs/package-check/blob/main/src/index.ts
   - check that exports are consistent for different conditions
   - check that "types" are resolved correctly
   - import priority
     - worker > browser, worker > node
     - deno > node
     - types > all 
     - private namespace (eg `my-package:wasm`) > standard conditions(?)
   - useless combinations
     - (worker AND require) is unlikely to trigger because workers are basically always a bundled or ESM environment
- [ ] refactor mode, snapshot all permutations and manually or automatically suggest simpler ways to organize the imports
  - maybe it is possible to use mathjs.simplify to reduce/flatten the conditions(?) or at least study how CAS systems reduce things 
  - we can normalized mutually exclusive to preferred condition then eliminate the shared settings
  - mathjs: need to tweak [associativity of logical operators](https://github.com/josdejong/mathjs/blob/d520b2404b3d7ffdd9ab710c9e1bb9043772cdc2/src/expression/operators.js#L40)?
  - sympy also supports this natively: https://docs.sympy.org/latest/modules/logic.html#simplification-and-equivalence-testing https://realpython.com/pyscript-python-in-browser/#third-party-libraries-bundled-with-pyodide
- [ ] coverage report, show conditions that would never be resolved
- [ ] define exports in a high level syntax that is compiled for you, eg: `(node AND worker) OR node-worker: { ... }` could compile to `{ node: { worker: { ...} }, 'node-worker': { ...} }`
- [ ] kind of another project idea, a yarn berry plugin to patch exports map according to high level syntax, eg, "move worker condition to top", or "make worker condition copy browser condition"
- [ ] create a survey (by script) of interesting exports
  - check httpie(?)
- [ ] add link to interesting related projects, like https://publint.dev/
- [ ] Review typescript documentation about moduleResolution again and make sure all use cases and import conditions are covered: https://www.typescriptlang.org/docs/handbook/modules/reference.html#the-moduleresolution-compiler-option

Interesting discussion: https://github.com/lukeed/resolve.exports/issues/12
